name: models
description: Data models and DTOs
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0