name: home_feature
description: Home screen feature module
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  services:
    path: ../../services
  models:
    path: ../../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0