name: services
description: API services and network utilities
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0