name: app
description: Main application package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  
  core:
    path: ../packages/core
  home_feature:
    path: ../packages/features/home
  details_feature:
    path: ../packages/features/details

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true